### ISSUE TITLE
Update method keeps adding "]]"

### ISSUE THREAD

**Issue by ramon86** [chhoumann/MetaEdit#95]
If I use the "update" method from the API on a field and use a link with double square brackets to link to another file, repeating the action results in extra occurrences of "]]" at the end.

Example:

```
TestProp:: 
```dataviewjs
const {update} = app.plugins.plugins["metaedit"].api;
const activeFile = app.workspace.getActiveFile();
await update('TestProp', '[[Test]]', activeFile);
\```
```

(remove that last backslash, can't get formatting to work :))

The expectation is that this page simply always sets TestProp to [[Test]], but the second time it becomes [[Test]]]], the third time [[Test]]]]]], fourth [[Test]]]]]]]] etc.

**Comment by jaerri** [comment]
Having the same issue rn, after looking around I believe the problem comes from this regex:
https://github.com/chhoumann/MetaEdit/blob/57883f619614fb2a359a9e94ac1484c8c8f7715e/src/metaController.ts#L340
![image](https://github.com/chhoumann/MetaEdit/assets/62021987/23c65744-1c22-4e80-9fd3-f5a84e51015c)
the regex only matches until the end of "value", which leaves the double square brackets behind

Proposed fix #96
